### ISSUE TITLE
ROS1 and Ubuntu 20.04

### ISSUE THREAD

**Issue by paaraujo** [SCU-RSL-ROS/radar_omnipresense#15]
Hi, I have an OPS-241A radar and I am trying to collect data from it using ROS1 inside Ubuntu 20.04. This is what I did:

1. Downloaded the repo and added to my catkin workspace;
2. Added the `include/rapidjson` folder to my `/usr/include` directory;
3. Gave read/write privileges to `/dev/ttyACM0`;
4. Built the workspace.

I can successfully launch the single radar node. However, when I run `rostopic echo /radar_report`, the cursor keeps blinking and nothing happen in the terminal. If I run `rostopic hz /radar_report`, it keeps saying _no new messages_. What am I missing? Thank you!

**Comment by omnipresense** [comment]
Hi paarujo, Just a quick check or question, is anything moving in front of the sensor?  If nothing is moving the sensor should not report any speeds detected and no messages are sent.  If you wave your hand in front of the sensor messages will be sent from the sensor.  Let us know if you see any messages within ROS with motion present.

**Comment by jimwhitfield** [comment]
A few years back I removed the dependency on rapidJson, so there should be no issues with that.  I just now removed the bit in the readme.md that mentioned it.

Glad you solved a port-permission problem.  That's a good way to solve the /dev/ttyACM0 permission issue so that it stays solved even after reboots and replugs. When you say "the communication error disappeared" are you saying that it works now?

Improvising a bit from the Readme, you can send commands to the radar.  I'm reasonably sure that the replies will be visible with `rostopic echo /radar_report` running.
For instance
rosservice call /radar_1/send_api_command "command: 'R?'"

**Comment by paaraujo** [comment]
I tried the `rosservice call /radar/send_api_command "command: 'R?'"` and I got an error: `ERROR: Service [/radar/send_api_command] is not available.`

The communication error happened when I launched the node. After I add the command the node didn't give me errors. However, I can't echo messages, the problem persists.

**Comment by jimwhitfield** [comment]
OK, I have put the driver on an ubuntu 20.04 ("focal") release after a clean install of ROS ("noetic")

**Comment by paaraujo** [comment]
Okay @jimwhitfield, thanks for the detailed answer. So, I try the "double make" call to see if the messages will be built. I think I tried that not intentionally, but I will check that and I will let you know the result. I have a 241A. When I call `rostopic echo /radar_report`, after the Enter, the cursor stays blinking in the next line and nothing appears. When I call `rostopic hz /radar_report`, I keep receiving the message __no new message__.

**Comment by paaraujo** [comment]
Hi @jimwhitfield, installed and built the drive following the documentation, just to record I am using this command:

`catkin_make -DPYTHON_EXECUTABLE=/usr/bin/python3`

It seems that the 5s rebooting issue was happening to me as well. So, I timed to launch the node and it seems that the communication was successfully established. However, I can't receive messages and the problem still persists :-(

Is there anything else I can't try to find the problem?

**Comment by jimwhitfield** [comment]
Glad to hear it's working!
The API calls like `rosservice call /radar/send_api_command "command: 'S2'"` should double the standard sampling rate (twice as fast => 2x the report frequency.  S2= 20k-samples per sec   SL = 50k/s)  but I haven't had success with that call yet. (A high priority override issue prevented any ROS investigation yesterday).  
Alternatively, you can forgo ROS for a moment and just connect directly to the com port the sensor is on using `screen /dev/ttyACM0` or minicom (or teraterm on a PC) to issue the `S2` or SL call, then save the setting persistently by `P!` and then the sensor will keep that rate after power cycles.  (As a general rule, once a sensor is configured, there's not been a pressing need to issue api commands, which is why that code may have stopped working without anyone being aware.)

**Comment by paaraujo** [comment]
Hi @jimwhitfield, I will try the commands. For now, I am getting about 6 measurements per second. I didn't get the `screen` command. After I start it, I just need to write `S2` + Enter in the terminal?

**Comment by jimwhitfield** [comment]
Yeah, `screen /dev/ttyACM0`  or `minicom -D /dev/ttyACM0` are both readily-available programs that can talk to /dev/ttyACM0 like a terminal.    (Either of them are installable with the command `sudo apt-get install screen` or `sudo apt-get install minicom`   minicom is more focused on being a terminal program.)   Note: Either of them show somewhat helpful menus with a ^A ^Z key sequence.  Note #2: From my memory, it might be that ^A ^X  may be the quit characters for both of them. 
Once you're connected to the sensor, `??` will show you many of your settings.  `S2` + Enter (or `SL`) will indeed change the sampling rate.    `P!` will save the setting.

**Comment by paaraujo** [comment]
Thanks! I will try that tomorrow in the lab and I will let you know the results.

**Comment by paaraujo** [comment]
Hi @jimwhitfield, good news! I tried `screen` and it worked. I noticed that the HZ inside ROS is different. For example, if I set `SX`, `rostopic echo /radar_report` will report an average frequency of around 6. If I set `S2`, I get ~16Hz. Is it related to ROS or does the radar itself work like that?

**Comment by jimwhitfield** [comment]
Yay! Those commands (SX, S2, SL) are API commands to change the settings on the radar.  (All commands are found in https://omnipresense.com/wp-content/uploads/2019/10/AN-010-Q_API_Interface.pdf )  

Also, it's cool to me that ROS is observing/confirming that the radar's report rate per second (hz) has doubled when moving from SX to S2

**Comment by jimwhitfield** [comment]
I added information about solving permission problems to the README, including the udev rules approach you referred to.  
I'm going to close this issue now.  Thanks for opening it in the first place.

**Comment by bclaw524** [comment]
> 

Hi, I'm having a similar issue running this on Noetic. I am not having any LED change when waving my hand over the lidar.

**Comment by omnipresense** [comment]
Hello blcaw524,

Can you provide more information about your setup, what sensor you are using and what configuration of the sensor are set?

Thanks,

Sandy

**Comment by bclaw524** [comment]
@omnipresense 

Hi. I managed to get the red/blue light to appear, turns out I had an error when trying to enable the relaxed privileges. I'm using a OPS243 on noetic. 

I tried connecting to it using minicom and I'm getting the following:
![Screenshot from 2023-01-26 09-00-52](https://user-images.githubusercontent.com/16769597/214731457-57178eaf-559f-466f-af6e-6fed939773d7.png)

Is this correct?
I also managed to get the settings menu open, but I'm not understanding how to send the api commands.

**Comment by omnipresense** [comment]
Hi, can you open a new issue on github?  Better to not mess with history on this old closed one.  

I do not know what you mean by "enable the relaxed privileges".

Good to know you're seeing data.  That's a very messed up flow of data.  I'm wondering if you also still have ROS running? (or two minicoms? two ros programs) because you're not seeing all the characters that the sensor puts out.  There should be commas between any consecutive numbers (like 2.4,2.4,2.4  ) and also after any "m" (meters).  Furthermore, there should be many more linefeeds.  There would never be more than one "m" on a line.  Lines should end with a number.
     
Sending API commands when interacting with the terminal is as simple as typing them in.  Typing ? ? should get you a whole bunch of data about the current settings.  You could even set some settings and then enter the A! command, the settings will persist across power loss.  

(Once you've got the sensor working well, then you can retry ros, and then you can use the ```rosservice call /send_api_command "command: 'S2'"``` to send commands (like S2 in this example)

**Comment by bclaw524** [comment]
@omnipresense 

The "enable relax privileges" was a fix in the error section of the readme (the echo kernel etc.)

Will make a new post. 
Thanks

**Comment by bclaw524** [comment]
@omnipresense 

Well...it fixed itself, somehow. dev/ttyACM0 bugged out and wouldn't detect. Moved to a different usb port and it worked. 

![Screenshot from 2023-01-26 10-07-38](https://user-images.githubusercontent.com/16769597/214742083-a6b4f2d9-d7f8-415c-a1f3-81fecb2f2bdc.png)

I can send commands through minicom too. No idea what caused the original issue

**Comment by omnipresense** [comment]
Glad to hear it.   I see it's switched over to JSON--something that the ROS library does.  There's still missing characters there in that output, so that's concerning about how well the driver will be able to parse the sensor output.
